global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'php-fpm'
    metrics_path: /metrics
    static_configs:
      - targets: ['php-fpm-exporter:9253']

  - job_name: 'opcache'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:80']

  - job_name: 'caddy'
    metrics_path: /metrics
    static_configs:
      - targets: ['franken:2019', 'franken-worker:2019']