{
 "title": "Caddy",
 "description": "Caddy HTTP server monitoring.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(caddy_http_requests_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests in flight",
   "type": "stat",
   "description": "The number of requests currently being handled by the server.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_requests_in_flight{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "description": "Total requests handled in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_requests_total{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "description": "Rate of requests handled per second in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median request duration",
   "type": "stat",
   "description": "Median round-trip request duration for the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median response duration",
   "type": "stat",
   "description": "Median time-to-first-byte response duration for the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_response_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total middleware errors",
   "type": "stat",
   "description": "A number of middleware errors encountered while handling requests in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_errors_total{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median request size",
   "type": "stat",
   "description": "Median request (estimated) size in bytes in the selected time range. Includes body.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_size_bytes_bucket{job=\"$job\",instance=\"$instance\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median response size",
   "type": "stat",
   "description": "Median returned response body size in bytes in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_response_size_bytes_bucket{job=\"$job\",instance=\"$instance\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests size",
   "type": "stat",
   "description": "Sum of the sizes of all received requests in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_size_bytes_sum{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total responses size",
   "type": "stat",
   "description": "Sum of sizes of all response bodies in the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_response_size_bytes_sum{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx response percentage",
   "type": "stat",
   "description": "Percentage of responses with 4xx status code in all responses.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_response_duration_seconds_count{job=\"$job\",instance=\"$instance\", code=~\"4..\"}[$__range])) / sum(increase(caddy_http_response_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx response percentage",
   "type": "stat",
   "description": "Percentage of responses with 4xx status code in all responses.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_response_duration_seconds_count{job=\"$job\",instance=\"$instance\", code=~\"5..\"}[$__range])) / sum(increase(caddy_http_response_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "FrankenPHP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Busy PHP Threads",
   "type": "stat",
   "description": "Number of busy PHP threads currently processing requests",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_busy_threads{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Busy Threads"
    }
   ]
  },
  {
   "title": "Total PHP Threads",
   "type": "stat",
   "description": "Total number of PHP threads available",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_total_threads{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total Threads"
    }
   ]
  },
  {
   "title": "Busy PHP Workers",
   "type": "stat",
   "description": "Number of busy PHP workers for this worker",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_busy_workers{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Total PHP Workers",
   "type": "stat",
   "description": "Total number of PHP workers for this worker",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_total_workers{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Ready PHP Workers",
   "type": "stat",
   "description": "Running workers that have successfully called frankenphp_handle_request at least once",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_ready_workers{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Request Queue Depth",
   "type": "stat",
   "description": "Number of regular queued requests waiting to be processed",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_queue_depth{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Queue Depth"
    }
   ]
  },
  {
   "title": "Worker Requests Total",
   "type": "stat",
   "description": "Total requests processed by PHP workers in the selected time range",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(frankenphp_worker_request_count{job=\"$job\",instance=\"$instance\"}[$__range]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Avg Worker Request Time",
   "type": "stat",
   "description": "Average request processing time per worker",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_worker_request_time{job=\"$job\",instance=\"$instance\"} / frankenphp_worker_request_count{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Avg Request Time"
    }
   ]
  },
  {
   "title": "Worker Restarts",
   "type": "stat",
   "description": "Number of PHP worker restarts",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frankenphp_worker_restarts{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Thread Utilization %",
   "type": "stat",
   "description": "Worker efficiency: percentage of threads that are busy",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(frankenphp_busy_threads{job=\"$job\",instance=\"$instance\"} / frankenphp_total_threads{job=\"$job\",instance=\"$instance\"}) * 100",
     "legendFormat": "Thread Utilization"
    }
   ]
  },
  {
   "title": "PHP Thread Utilization",
   "type": "timeseries",
   "description": "PHP thread utilization over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "frankenphp_busy_threads{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Busy Threads"
    },
    {
     "expr": "frankenphp_total_threads{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total Threads"
    }
   ]
  },
  {
   "title": "PHP Worker Status & Queue",
   "type": "timeseries",
   "description": "PHP worker utilization and queue depth over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "frankenphp_busy_workers{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Busy Workers"
    },
    {
     "expr": "frankenphp_ready_workers{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Ready Workers"
    },
    {
     "expr": "frankenphp_queue_depth{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Queue Depth"
    }
   ]
  },
  {
   "title": "Worker Request Rate",
   "type": "timeseries",
   "description": "Worker request rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(frankenphp_worker_request_count{job=\"$job\",instance=\"$instance\"}[$interval])",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Average Worker Request Time",
   "type": "timeseries",
   "description": "Average request processing time per worker over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "frankenphp_worker_request_time{job=\"$job\",instance=\"$instance\"} / frankenphp_worker_request_count{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  { "title": "Detailed metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Rate of requests by HTTP method (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[$interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP status breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[$__range])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP method breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$interval])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(caddy_http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$interval])) by (le))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(caddy_http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$interval])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$interval])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Data transfer rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_size_bytes_sum{job=\"$job\",instance=\"$instance\"}[$interval]))",
     "legendFormat": "request"
    },
    {
     "expr": "-sum(rate(caddy_http_response_size_bytes_sum{job=\"$job\",instance=\"$instance\"}[$interval]))",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Rate of 4xx and 5xx responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{job=\"$job\",instance=\"$instance\", code=~\"4..|5..\"}[$interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Middleware error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(caddy_http_request_errors_total{job=\"$job\",instance=\"$instance\"}[$interval])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request duration heatmap",
     "type": "heatmap",
     "description": "Round-trip request duration heatmap.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 155 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_request_size_bytes_bucket{job=\"$job\",instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response duration heatmap",
     "type": "heatmap",
     "description": "Response time-to-first-byte heatmap.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 165 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_response_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 165 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_response_size_bytes_bucket{job=\"$job\",instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}